import java.rmi.AccessException;

public class Exception {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
int sum=100/0;
	}
catch(ArithmeticException e) {
	System.out.println("errors occured");
	System.out.println("rest of the code");
	
}
}}
